"""
Prescription Studio - Universal Data Models

Medico-legally valid prescription schema used by both frontend and backend.
India-ready format with all required fields for legal compliance.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import List, Optional, Tuple

from pydantic import BaseModel, Field, field_validator


class PrescriptionStatus(str, Enum):
    DRAFT = "draft"
    LOCKED = "locked"


class Doctor(BaseModel):
    """Doctor information - required for medico-legal validity"""
    name: str = Field(..., min_length=2, description="Doctor's full name")
    qualification: str = Field(default="", description="e.g., MBBS, MD, DNB")
    registration_no: str = Field(..., min_length=3, description="Medical council registration number")
    clinic: str = Field(default="", description="Clinic/Hospital name")
    phone: str = Field(default="", description="Contact number")
    email: str = Field(default="", description="Email address")


class Patient(BaseModel):
    """Patient information - required for prescription validity"""
    name: str = Field(..., min_length=2, description="Patient's full name")
    age: int = Field(..., ge=0, le=150, description="Age in years")
    sex: str = Field(..., description="M / F / Other")
    id: Optional[str] = Field(default=None, description="Patient ID / UHID")
    phone: Optional[str] = Field(default=None, description="Contact number")
    address: Optional[str] = Field(default=None, description="Address")
    
    @field_validator("sex")
    @classmethod
    def validate_sex(cls, v: str) -> str:
        v = (v or "").strip().upper()
        if v not in ("M", "F", "MALE", "FEMALE", "OTHER"):
            raise ValueError("Sex must be M, F, or Other")
        return v[0] if v in ("MALE", "FEMALE") else v


class Visit(BaseModel):
    """Visit details"""
    visit_datetime: datetime = Field(default_factory=datetime.utcnow)
    complaints: List[str] = Field(default_factory=list)
    vitals: Optional[str] = Field(default=None, description="Vitals summary")
    examination: Optional[str] = Field(default=None, description="Physical examination findings")


class Diagnosis(BaseModel):
    """Diagnosis information"""
    primary: str = Field(default="", description="Primary diagnosis")
    provisional: List[str] = Field(default_factory=list, description="Provisional diagnoses / differentials")
    icd_codes: List[str] = Field(default_factory=list, description="ICD-10 codes if applicable")


class RxItem(BaseModel):
    """
    Individual medication item in the prescription.
    
    Fields follow standard prescription format:
    Drug Name (Generic/Brand) | Strength | Form | Dose | Frequency | Duration | Timing | Route | Instructions
    """
    generic: str = Field(..., min_length=2, description="Generic drug name (mandatory)")
    brand: Optional[str] = Field(default=None, description="Brand name (optional)")
    strength: Optional[str] = Field(default=None, description="e.g., 500mg, 10mg/5ml")
    form: Optional[str] = Field(default=None, description="Tab, Cap, Syr, Inj, Drops, Cream, etc.")
    dose: Optional[str] = Field(default=None, description="e.g., 1 tablet, 5ml, 2 puffs")
    frequency: str = Field(..., description="OD, BD, TDS, QID, HS, SOS, PRN, STAT, etc.")
    timing: Optional[str] = Field(default=None, description="Before food, After food, With food, Empty stomach")
    duration: Optional[str] = Field(default=None, description="5 days, 1 week, 2 weeks, 1 month, etc.")
    route: Optional[str] = Field(default=None, description="Oral, IV, IM, SC, Topical, Inhalation, etc.")
    instructions: Optional[str] = Field(default=None, description="Additional instructions")
    
    @field_validator("frequency")
    @classmethod
    def validate_frequency(cls, v: str) -> str:
        v = (v or "").strip().upper()
        valid = {"OD", "BD", "TDS", "QID", "HS", "SOS", "PRN", "STAT",
                 "ONCE DAILY", "TWICE DAILY", "THRICE DAILY", "Q4H", "Q6H", "Q8H", "Q12H",
                 "WEEKLY", "ALTERNATE DAYS", "AS NEEDED", "BEFORE MEALS", "AFTER MEALS"}
        if not v:
            raise ValueError("Frequency is required")
        return v


class SafetyAlert(BaseModel):
    """Safety alert generated by the system"""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    type: str = Field(..., description="duplicate, interaction, contraindication, allergy, dose_check")
    severity: str = Field(..., description="high, moderate, low")
    message: str = Field(..., description="Alert message")
    related_drugs: List[str] = Field(default_factory=list)
    rule_id: Optional[str] = Field(default=None, description="ID of rule that triggered this alert")


class SafetyOverride(BaseModel):
    """Doctor's override of a safety alert with mandatory reason"""
    alert_id: str = Field(..., description="ID of the alert being overridden")
    reason: str = Field(..., min_length=10, description="Reason for override (mandatory, min 10 chars)")
    overridden_at: datetime = Field(default_factory=datetime.utcnow)
    overridden_by: Optional[str] = Field(default=None, description="Doctor name/ID who overrode")


class LockInfo(BaseModel):
    """Lock information for finalized prescriptions"""
    locked_at: datetime = Field(default_factory=datetime.utcnow)
    locked_by: Optional[str] = Field(default=None, description="Doctor name who locked")
    hash: str = Field(..., description="SHA256 hash of canonical prescription JSON")
    pdf_path: Optional[str] = Field(default=None, description="Path to generated PDF")


class PrescriptionDraft(BaseModel):
    """
    Complete prescription document.
    
    This is the universal schema used throughout the system.
    All fields required for India medico-legal compliance are marked as required.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    status: PrescriptionStatus = Field(default=PrescriptionStatus.DRAFT)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    # Required for medico-legal validity
    doctor: Doctor
    patient: Patient
    visit: Visit
    
    # Clinical content
    diagnosis: Diagnosis = Field(default_factory=Diagnosis)
    rx_items: List[RxItem] = Field(default_factory=list)
    investigations: List[str] = Field(default_factory=list, description="Recommended tests")
    advice: List[str] = Field(default_factory=list, description="General advice / precautions")
    follow_up: Optional[str] = Field(default=None, description="Follow-up instructions")
    
    # Safety
    safety_alerts: List[SafetyAlert] = Field(default_factory=list)
    safety_overrides: List[SafetyOverride] = Field(default_factory=list)
    
    # Lock info (only present when status=locked)
    lock: Optional[LockInfo] = Field(default=None)
    
    # Metadata
    notes: Optional[str] = Field(default=None, description="Internal notes (not printed)")
    transcript: Optional[str] = Field(default=None, description="Original voice transcript if used")
    
    def can_lock(self) -> Tuple[bool, List[str]]:
        """
        Check if prescription can be locked.
        Returns (can_lock, list_of_errors)
        """
        errors = []
        
        # Doctor validation
        if not self.doctor.name or len(self.doctor.name.strip()) < 2:
            errors.append("Doctor name is required")
        if not self.doctor.registration_no or len(self.doctor.registration_no.strip()) < 3:
            errors.append("Doctor registration number is required")
        
        # Patient validation
        if not self.patient.name or len(self.patient.name.strip()) < 2:
            errors.append("Patient name is required")
        if self.patient.age is None or self.patient.age < 0:
            errors.append("Valid patient age is required")
        if not self.patient.sex:
            errors.append("Patient sex is required")
        
        # Visit validation
        if not self.visit.visit_datetime:
            errors.append("Visit date/time is required")
        
        # Prescription content validation
        has_meds = len(self.rx_items) > 0
        has_no_meds_note = any("no medicine" in (a or "").lower() for a in self.advice)
        
        if not has_meds and not has_no_meds_note:
            errors.append("At least one medication OR explicit 'No medicines prescribed' in advice is required")
        
        # Check for unresolved high-severity alerts
        overridden_ids = {o.alert_id for o in self.safety_overrides}
        unresolved_high = [a for a in self.safety_alerts 
                          if a.severity == "high" and a.id not in overridden_ids]
        if unresolved_high:
            errors.append(f"Unresolved high-severity safety alerts: {len(unresolved_high)}")
        
        return len(errors) == 0, errors


# Request/Response models for API endpoints

class CreateDraftRequest(BaseModel):
    """Request to create a new prescription draft"""
    doctor: Doctor
    patient: Patient
    visit: Optional[Visit] = None
    diagnosis: Optional[Diagnosis] = None
    transcript: Optional[str] = None


class UpdateDraftRequest(BaseModel):
    """Request to update an existing draft"""
    doctor: Optional[Doctor] = None
    patient: Optional[Patient] = None
    visit: Optional[Visit] = None
    diagnosis: Optional[Diagnosis] = None
    rx_items: Optional[List[RxItem]] = None
    investigations: Optional[List[str]] = None
    advice: Optional[List[str]] = None
    follow_up: Optional[str] = None
    safety_overrides: Optional[List[SafetyOverride]] = None
    notes: Optional[str] = None
    transcript: Optional[str] = None


class ParseRequest(BaseModel):
    """Request to parse free text into structured prescription data"""
    text: str = Field(..., min_length=3)
    context: Optional[dict] = None


class SuggestRequest(BaseModel):
    """Request for inline suggestions"""
    field: str = Field(..., description="drug, frequency, duration, timing, instruction, diagnosis")
    text: str = Field(..., min_length=1)
    limit: int = Field(default=8, ge=1, le=20)
    context: Optional[dict] = None


class SuggestResponse(BaseModel):
    """Response with suggestions"""
    suggestions: List[dict] = Field(default_factory=list)


class SafetyCheckRequest(BaseModel):
    """Request to run safety checks on prescription"""
    rx_items: List[RxItem]
    patient: Patient
    existing_alerts: List[SafetyAlert] = Field(default_factory=list)


class SafetyCheckResponse(BaseModel):
    """Response with safety check results"""
    alerts: List[SafetyAlert]
    overall_risk: str = Field(default="low", description="low, moderate, high")


class LockRequest(BaseModel):
    """Request to lock a prescription"""
    confirm: bool = Field(default=False, description="Must be true to proceed with lock")


class LockResponse(BaseModel):
    """Response after locking"""
    success: bool
    hash: Optional[str] = None
    errors: List[str] = Field(default_factory=list)


class PDFResponse(BaseModel):
    """Response with PDF generation result"""
    success: bool
    pdf_path: Optional[str] = None
    errors: List[str] = Field(default_factory=list)
