# backend/app/rag/extractors/base.py
"""
Base module for Dual-Mode Response Schema.

DOCTOR GRADE RULE: Every response MUST contain:
1. evidence_based: Content extracted ONLY from RAG sources (never invented)
2. llm_guided: Content generated by LLM when evidence is insufficient
3. coverage: Section scores, fallback status, and reason

The UI MUST render BOTH sections with clear labels:
- "EVIDENCE-BASED" - from textbook sources
- "LLM-GUIDED (VERIFY LOCALLY)" - generated when evidence insufficient

THIS IS NON-NEGOTIABLE.
"""
from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, TypedDict

from openai import OpenAI


# =============================================================================
# LLM CLIENT
# =============================================================================

LLM_MODEL = os.getenv("OPENAI_CHAT_MODEL", "gpt-4.1")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")


def get_llm() -> OpenAI:
    """Get OpenAI client."""
    if not OPENAI_API_KEY:
        raise RuntimeError("OPENAI_API_KEY not set")
    return OpenAI(api_key=OPENAI_API_KEY)


# =============================================================================
# SOURCE LABELS
# =============================================================================

class SourceLabel(str, Enum):
    """Source label for content origin."""
    EVIDENCE_BASED = "EVIDENCE-BASED"
    LLM_GUIDED = "LLM-GUIDED (VERIFY LOCALLY)"


# =============================================================================
# COVERAGE TYPES
# =============================================================================

class CoverageInfo(TypedDict):
    """Coverage information for a response."""
    section_scores: Dict[str, float]
    fallback_used: bool
    reason: str
    evidence_chunk_count: int
    fallback_sections: List[str]


# =============================================================================
# DUAL MODE RESPONSE TYPES
# =============================================================================

@dataclass
class LabeledContent:
    """Content with source label."""
    content: Any  # The actual content (string, list, dict, etc.)
    source_label: SourceLabel
    evidence_chunk_ids: List[str] = field(default_factory=list)
    confidence: float = 1.0  # 1.0 for evidence, < 1.0 for LLM-guided


@dataclass
class DualModeSection:
    """A section that can have evidence-based and/or LLM-guided content."""
    key: str
    title: str
    evidence_based: Optional[Any] = None
    llm_guided: Optional[Any] = None
    evidence_chunk_ids: List[str] = field(default_factory=list)
    fallback_used: bool = False
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "key": self.key,
            "title": self.title,
            "evidence_based": self.evidence_based,
            "llm_guided": self.llm_guided,
            "evidence_chunk_ids": self.evidence_chunk_ids,
            "fallback_used": self.fallback_used,
            "source_label": (
                SourceLabel.LLM_GUIDED.value if self.fallback_used and self.llm_guided
                else SourceLabel.EVIDENCE_BASED.value
            ),
        }


# =============================================================================
# DUAL MODE RESPONSE BASE
# =============================================================================

class DualModeResponseBase:
    """
    Base class for dual-mode responses.
    
    Ensures every feature response has:
    - evidence_based: RAG-extracted content
    - llm_guided: Fallback content when evidence insufficient
    - coverage: Section coverage info
    """
    
    def __init__(
        self,
        evidence_based: Dict[str, Any],
        llm_guided: Dict[str, Any],
        coverage: CoverageInfo,
        evidence_chunks: List[Dict[str, Any]] = None,
    ):
        self.evidence_based = evidence_based
        self.llm_guided = llm_guided
        self.coverage = coverage
        self.evidence_chunks = evidence_chunks or []
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "evidence_based": self.evidence_based,
            "llm_guided": self.llm_guided,
            "coverage": self.coverage,
            "evidence": [
                {
                    "chunk_id": ch.get("chunk_id") or ch.get("content_hash") or "",
                    "book": ch.get("book") or ch.get("book_id"),
                    "chapter": ch.get("chapter") or ch.get("section_path"),
                    "page_start": ch.get("page_start"),
                    "snippet": (ch.get("text") or "")[:400],
                }
                for ch in self.evidence_chunks[:25]
            ],
        }
    
    @classmethod
    def merge_sections(
        cls,
        evidence_sections: Dict[str, Any],
        llm_sections: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Merge evidence and LLM sections, preferring evidence where available.
        Returns combined dict with source labels.
        """
        merged = {}
        all_keys = set(evidence_sections.keys()) | set(llm_sections.keys())
        
        for key in all_keys:
            ev_val = evidence_sections.get(key)
            llm_val = llm_sections.get(key)
            
            # Determine which value to use and set source label
            if ev_val and _has_content(ev_val):
                merged[key] = {
                    "value": ev_val,
                    "source_label": SourceLabel.EVIDENCE_BASED.value,
                    "fallback_used": False,
                }
            elif llm_val and _has_content(llm_val):
                merged[key] = {
                    "value": llm_val,
                    "source_label": SourceLabel.LLM_GUIDED.value,
                    "fallback_used": True,
                }
            else:
                merged[key] = {
                    "value": None,
                    "source_label": None,
                    "fallback_used": False,
                }
        
        return merged


def _has_content(val: Any) -> bool:
    """Check if a value has meaningful content."""
    if val is None:
        return False
    if isinstance(val, str):
        return bool(val.strip()) and val.lower() not in [
            "not found in sources",
            "insufficient evidence",
            "not specified",
            "none",
            "",
        ]
    if isinstance(val, (list, dict)):
        return bool(val)
    return True


# =============================================================================
# LLM FALLBACK PROMPTS
# =============================================================================

# These prompts are used when RAG evidence is insufficient.
# They are designed to generate CONSERVATIVE, CLEARLY LABELED content.

TREATMENT_FALLBACK_SYSTEM = """You are a clinical decision support assistant generating CONSERVATIVE treatment guidance.

CRITICAL RULES:
1. This is FALLBACK content when textbook evidence is insufficient
2. Every response MUST include warnings to verify locally
3. Use CONSERVATIVE doses (start low, titrate up)
4. When uncertain, say "Verify with local guidelines"
5. Never claim this is from textbooks - it's LLM-generated guidance
6. Include standard monitoring recommendations
7. List common contraindications
8. If condition is serious, recommend specialist consultation"""

DDX_FALLBACK_SYSTEM = """You are a clinical decision support assistant generating differential diagnosis guidance.

CRITICAL RULES:
1. This is FALLBACK content when textbook evidence is insufficient
2. Always include life-threatening diagnoses in must-not-miss
3. Generate differential based on clinical reasoning, not random guesses
4. Include red flags and when to escalate
5. Recommend appropriate investigations
6. Never claim this is from textbooks - it's LLM-generated guidance
7. When uncertain about a diagnosis, say so explicitly"""

DRUG_FALLBACK_SYSTEM = """You are a clinical pharmacology assistant generating drug information.

CRITICAL RULES:
1. This is FALLBACK content when textbook evidence is insufficient
2. Use CONSERVATIVE dose recommendations
3. Always include major contraindications
4. Always include serious adverse effects
5. Include drug class and mechanism if known
6. Recommend monitoring
7. Never claim this is from textbooks - it's LLM-generated guidance
8. Mark doses with "VERIFY DOSE" warning"""


def generate_fallback_content(
    *,
    feature: str,  # "treatment" | "ddx" | "drug" | "interaction"
    topic: str,
    context: Dict[str, Any],
    sections_needed: List[str],
) -> Dict[str, Any]:
    """
    Generate LLM fallback content when RAG evidence is insufficient.
    
    This content is CLEARLY LABELED as LLM-guided and includes
    verification warnings.
    
    Args:
        feature: Which feature needs fallback
        topic: The medical topic
        context: Patient/clinical context
        sections_needed: Which sections need fallback content
    
    Returns:
        Dict with section content, all labeled as LLM-guided
    """
    if not OPENAI_API_KEY:
        return _empty_fallback_content(sections_needed)
    
    # Select appropriate system prompt
    system_prompts = {
        "treatment": TREATMENT_FALLBACK_SYSTEM,
        "ddx": DDX_FALLBACK_SYSTEM,
        "drug": DRUG_FALLBACK_SYSTEM,
        "interaction": DRUG_FALLBACK_SYSTEM,
    }
    system = system_prompts.get(feature, TREATMENT_FALLBACK_SYSTEM)
    
    # Build user prompt
    user_prompt = _build_fallback_user_prompt(feature, topic, context, sections_needed)
    
    try:
        llm = get_llm()
        resp = llm.chat.completions.create(
            model=LLM_MODEL,
            temperature=0.2,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user_prompt},
            ],
        )
        raw = resp.choices[0].message.content or ""
        
        # Parse JSON response
        json_match = re.search(r"\{[\s\S]*\}", raw)
        if json_match:
            content = json.loads(json_match.group())
            # Add LLM-guided labels to all content
            return _label_fallback_content(content)
    except Exception as e:
        pass
    
    return _empty_fallback_content(sections_needed)


def _build_fallback_user_prompt(
    feature: str,
    topic: str,
    context: Dict[str, Any],
    sections_needed: List[str],
) -> str:
    """Build the user prompt for fallback generation."""
    if feature == "treatment":
        return f"""Generate CONSERVATIVE treatment guidance for: {topic}

Patient context: {json.dumps(context) if context else 'Not specified'}

Generate content for these sections: {', '.join(sections_needed)}

Return strict JSON matching this schema:
{{
  "summary_plan": ["Goal 1", "Goal 2"],
  "first_line_regimens": [
    {{
      "label": "Regimen description",
      "drugs": [
        {{
          "generic": "drug name",
          "dose": "CONSERVATIVE dose - VERIFY LOCALLY",
          "route": "PO/IV",
          "frequency": "frequency",
          "duration": "duration",
          "verify_dose_warning": true
        }}
      ]
    }}
  ],
  "second_line_regimens": [...],
  "contraindications_and_cautions": ["Important caution 1"],
  "monitoring": ["What to monitor"],
  "red_flags_urgent_referral": ["When to escalate"],
  "follow_up": ["Follow-up recommendation"],
  "llm_generated_warning": "This is LLM-generated guidance. Verify with local guidelines."
}}"""
    
    elif feature == "ddx":
        return f"""Generate differential diagnosis for symptoms: {topic}

Patient context: {json.dumps(context) if context else 'Not specified'}

Generate content for these sections: {', '.join(sections_needed)}

Return strict JSON:
{{
  "must_not_miss": [
    {{
      "diagnosis": "diagnosis name",
      "key_clues": ["clue 1", "clue 2"],
      "immediate_actions": ["action 1"]
    }}
  ],
  "ranked_ddx": [
    {{
      "diagnosis": "diagnosis name",
      "likelihood": "high|medium|low",
      "for": ["supporting feature"],
      "against": ["argument against"],
      "discriminating_tests": ["test 1"]
    }}
  ],
  "rapid_algorithm": {{
    "step_1": ["immediate action"],
    "step_2": ["next action"],
    "step_3": ["if unclear"]
  }},
  "red_flags": ["red flag 1"],
  "llm_generated_warning": "This is LLM-generated guidance. Verify with clinical assessment."
}}"""
    
    elif feature in ["drug", "interaction"]:
        return f"""Generate drug information for: {topic}

Patient context: {json.dumps(context) if context else 'Not specified'}

Generate content for these sections: {', '.join(sections_needed)}

Return strict JSON:
{{
  "indications": ["indication 1"],
  "dosing": {{
    "adult": [
      {{
        "indication": "for what",
        "dose": "CONSERVATIVE dose - VERIFY LOCALLY",
        "route": "route",
        "frequency": "frequency",
        "verify_dose_warning": true
      }}
    ]
  }},
  "contraindications": ["contraindication 1"],
  "adverse_effects": {{
    "common": ["effect 1"],
    "serious": ["serious effect 1"]
  }},
  "monitoring": ["what to monitor"],
  "llm_generated_warning": "This is LLM-generated guidance. Verify with pharmacist/formulary."
}}"""
    
    return "{}"


def _label_fallback_content(content: Dict[str, Any]) -> Dict[str, Any]:
    """Add LLM-guided labels to all fallback content."""
    content["_source_label"] = SourceLabel.LLM_GUIDED.value
    content["_is_fallback"] = True
    
    # Add warnings to dose fields
    def add_dose_warning(obj):
        if isinstance(obj, dict):
            if "dose" in obj and obj.get("dose"):
                obj["verify_dose_warning"] = True
                if not obj["dose"].endswith("- VERIFY LOCALLY"):
                    obj["dose"] = obj["dose"] + " - VERIFY LOCALLY"
            for v in obj.values():
                add_dose_warning(v)
        elif isinstance(obj, list):
            for item in obj:
                add_dose_warning(item)
    
    add_dose_warning(content)
    return content


def _empty_fallback_content(sections_needed: List[str]) -> Dict[str, Any]:
    """Return empty fallback content with structure."""
    content = {
        "_source_label": SourceLabel.LLM_GUIDED.value,
        "_is_fallback": True,
        "_fallback_failed": True,
        "llm_generated_warning": "Unable to generate fallback content. Please consult local guidelines.",
    }
    for section in sections_needed:
        content[section] = []
    return content


# =============================================================================
# DOSE EXTRACTION
# =============================================================================

# Regex patterns for extracting doses
DOSE_PATTERNS = [
    # Standard dose patterns
    r"(\d+(?:\.\d+)?)\s*(mg|mcg|g|ml|units?|iu)\s*(?:per\s+)?(?:dose|day)?",
    # Weight-based
    r"(\d+(?:\.\d+)?)\s*(mg|mcg|g|ml|units?)/kg",
    # Frequency patterns
    r"(\d+(?:\.\d+)?)\s*(mg|mcg|g|ml|units?)\s*(bd|tds|qds|qid|tid|bid|od|once\s+daily|twice\s+daily)",
    # Range patterns
    r"(\d+(?:\.\d+)?)\s*(?:to|-)\s*(\d+(?:\.\d+)?)\s*(mg|mcg|g|ml|units?)",
]


def extract_doses_from_text(text: str) -> List[Dict[str, Any]]:
    """
    Extract structured dose information from text.
    
    Returns list of dose objects with:
    - value: numeric dose value
    - unit: mg, mcg, g, etc.
    - frequency: if found
    - weight_based: True if per kg dose
    - raw_text: original matched text
    """
    doses = []
    text_lower = text.lower()
    
    for pattern in DOSE_PATTERNS:
        for match in re.finditer(pattern, text_lower, re.IGNORECASE):
            groups = match.groups()
            dose_obj = {
                "raw_text": match.group(0),
                "value": float(groups[0]) if groups[0] else None,
                "unit": groups[1] if len(groups) > 1 else None,
                "frequency": groups[2] if len(groups) > 2 else None,
                "weight_based": "/kg" in match.group(0),
            }
            doses.append(dose_obj)
    
    return doses


def validate_dose_reasonableness(
    drug_name: str,
    dose_value: float,
    unit: str,
) -> bool:
    """
    Basic validation that a dose is within reasonable range.
    Returns True if dose seems reasonable.
    """
    # Common drug max daily doses (simplified)
    MAX_DOSES = {
        "paracetamol": 4000,  # mg
        "acetaminophen": 4000,
        "ibuprofen": 2400,
        "amoxicillin": 6000,
        "metformin": 2550,
        "lisinopril": 80,
        "amlodipine": 10,
        "atorvastatin": 80,
        "omeprazole": 40,
        "aspirin": 4000,
    }
    
    drug_lower = drug_name.lower()
    for known_drug, max_dose in MAX_DOSES.items():
        if known_drug in drug_lower:
            if unit.lower() in ["mg", "milligram"]:
                return dose_value <= max_dose
    
    # Default: if dose seems very high, flag it
    if unit.lower() in ["mg", "milligram"] and dose_value > 10000:
        return False
    
    return True


# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

def strip_citations_from_text(text: str) -> str:
    """Strip any citation references from text."""
    patterns = [
        r"\bSources?\s*:\s*.*?$",
        r"\[\d+\]",
        r"\(p\.?\s*\d+\)",
        r"\bpage\s+\d+\b",
        r"\bChapter\s+\d+",
        r"\bSee\s+also\b.*$",
        r"\bFurther\s+reading\b.*$",
    ]
    
    result = text
    for pattern in patterns:
        result = re.sub(pattern, "", result, flags=re.IGNORECASE | re.MULTILINE)
    
    result = re.sub(r"\n{3,}", "\n\n", result)
    return result.strip()


def ensure_section_complete(
    section_content: Any,
    section_type: str,
) -> Any:
    """
    Ensure a section has complete, non-empty content.
    If empty, return placeholder with instruction.
    """
    if _has_content(section_content):
        return section_content
    
    # Return appropriate placeholder based on section type
    placeholders = {
        "dose": [{"generic": "Verify dose", "dose": "VERIFY LOCALLY", "verify_dose_warning": True}],
        "regimen": [{"label": "Treatment regimen", "drugs": [], "note": "Insufficient evidence - consult local guidelines"}],
        "list": ["Insufficient evidence in sources - verify locally"],
        "text": "Insufficient evidence in sources - verify locally",
    }
    
    return placeholders.get(section_type, placeholders["list"])
